#!/bin/bash
# mkdir -p checkpoints/raft_uncertainty

# python -u train.py --name train_raft-chairs-uncertainty --checkpoint_out=../checkpoints/raft_uncertainty --stage chairs --validation chairs --gpus 0 --num_steps 100000 --batch_size 10 --lr 0.0004 --image_size 368 496 --wdecay 0.0001 --uncertainty true
# python -u train.py --name train_raft-things-uncertainty --checkpoint_out=../checkpoints/raft_uncertainty --stage things --validation sintel --restore_ckpt ../checkpoints/raft_uncertainty/raft-chairs.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.000125 --image_size 400 720 --wdecay 0.0001 --uncertainty true
# python -u train.py --small --name train_raft_small_sintel --stage sintel --validation sintel --restore_ckpt checkpoints/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.000125 --image_size 368 768 --wdecay 0.00001 --gamma=0.85
# python -u train.py --small --name train_raft_small_kitti  --stage kitti --validation kitti --restore_ckpt checkpoints/raft-sintel.pth --gpus 0 --num_steps 50000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85


# python -u train.py --name overfit_raft_viper_100_random_samples_semantic_v3 --num_overfit_samples 100 --validation_set_size 10 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/overfit_raft_viper_100_random_samples_semantic_v1 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 5000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 1234 --semantic_loss true
# python -u train.py --name overfit_raft_viper_100_random_samples_semantic_v1_seed_0 --num_overfit_samples 100 --validation_set_size 10 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/overfit_raft_viper_100_random_samples_semantic_v1_seed_0 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 5000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 0 --semantic_loss true
# python -u train.py --name overfit_raft_viper_100_random_samples_semantic_v1_seed_42 --num_overfit_samples 100 --validation_set_size 10 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/overfit_raft_viper_100_random_samples_semantic_v1_seed_42 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 5000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 42 --semantic_loss true

# python -u train.py --name raft_viper_baseline_seed_0 --validation_set_size 200 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/raft_viper_baseline_seed_0 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 0 --mixed_precision
# python -u train.py --name raft_viper_baseline_seed_42 --validation_set_size 200 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/raft_viper_baseline_seed_42 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 42 --mixed_precision
# python -u train.py --name raft_viper_baseline_seed_1234 --validation_set_size 200 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/raft_viper_baseline_seed_1234 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 1234 --mixed_precision

# python -u train.py --name raft_viper_semantic_v1_seed_0 --validation_set_size 200 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/raft_viper_semantic_v1_seed_0 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 0 --mixed_precision --semantic_loss true
# python -u train.py --name raft_viper_semantic_v1_seed_42 --validation_set_size 200 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/raft_viper_semantic_v1_seed_42 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 42 --mixed_precision --semantic_loss true
# python -u train.py --name raft_viper_semantic_v1_seed_1234 --validation_set_size 200 --stage viper --validation viper --checkpoint_out ../checkpoints/raft_semantic/raft_viper_semantic_v1_seed_1234 --restore_ckpt ../models/raft_original_models/raft-things.pth --gpus 0 --num_steps 100000 --batch_size 6 --lr 0.0001 --image_size 288 960 --wdecay 0.00001 --gamma=0.85 --seed 1234 --mixed_precision --semantic_loss true
